#![no_std]
//! Reflector adapter — typed clients for the Reflector price-oracle contract
//! and the Reflector subscription contract, plus helpers that normalize prices
//! into the project's [`PRICE_SCALE`] (1e10).
//!
//! Two foreign contracts are wrapped:
//!
//! 1. **Price oracle** (`reflector-network/reflector-contract`, e.g. the `pulse-contract`
//!    or `beam-contract` deployments). Synchronous reads of `lastprice(asset) -> PriceData`
//!    using a `decimals()`-derived rescale to PRICE_SCALE.
//! 2. **Subscription contract** (`reflector-network/reflector-subscription-contract`).
//!    Webhook-driven push notifications when a base/quote pair crosses a threshold.
//!    Used by the position manager for TP/SL/liq triggers.
//!
//! `ReflectorAsset` is the local mirror of `oracle::types::Asset` and
//! `ReflectorPriceData` mirrors `oracle::types::PriceData`. Local re-declarations
//! keep this crate decoupled from Reflector's source repo while preserving the
//! exact `#[contracttype]` layout the deployed contracts use.
//!
//! For test-time substitution, the position manager calls into this adapter via
//! [`OracleSource`] / [`SubscriptionSource`] traits. A mock implementation lives
//! in `mock.rs` (task 1.14).

use soroban_sdk::{contractclient, contracttype, Address, Bytes, Env, String, Symbol, Vec};

use math::errors::MathError;
use math::scale::PRICE_SCALE;

#[cfg(any(test, feature = "testutils"))]
pub mod mock;

// ────────────────────────────────────────────────────────────────────────────
// Mirror types (must match Reflector's `#[contracttype]` ABI bit-for-bit)
// ────────────────────────────────────────────────────────────────────────────

/// Mirrors `oracle::types::Asset` from `reflector-network/reflector-contract`.
///
/// Variants must stay in lockstep with the deployed oracle contract or the
/// host will fail to deserialize the call argument.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ReflectorAsset {
    Stellar(Address),
    Other(Symbol),
}

/// Mirrors `oracle::types::PriceData`. The `price` field uses the oracle's own
/// scale (see `decimals()`), NOT the project's `PRICE_SCALE`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReflectorPriceData {
    pub price: i128,
    pub timestamp: u64,
}

/// Mirrors `reflector-subscription-contract::types::ticker_asset::TickerAsset`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TickerAsset {
    pub asset: String,
    pub source: String,
}

/// Mirrors `reflector-subscription-contract::types::subscription_init_params::SubscriptionInitParams`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SubscriptionInitParams {
    pub owner: Address,
    pub base: TickerAsset,
    pub quote: TickerAsset,
    /// Price-movement threshold in ‰ (per-mille).
    pub threshold: u32,
    /// Heartbeat interval in minutes (Reflector floors at 5).
    pub heartbeat: u32,
    /// Encrypted webhook payload, ≤ 2048 bytes.
    pub webhook: Bytes,
}

/// Mirrors `reflector-subscription-contract::types::subscription_status::SubscriptionStatus`.
#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum SubscriptionStatus {
    Active = 0,
    Suspended = 1,
}

/// Mirrors `reflector-subscription-contract::types::subscription::Subscription`.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Subscription {
    pub owner: Address,
    pub base: TickerAsset,
    pub quote: TickerAsset,
    pub threshold: u32,
    pub heartbeat: u32,
    pub webhook: Bytes,
    pub balance: u64,
    pub status: SubscriptionStatus,
    pub updated: u64,
}

// ────────────────────────────────────────────────────────────────────────────
// Foreign contract clients (generated by `#[contractclient]` macro)
// ────────────────────────────────────────────────────────────────────────────

/// Read-only price-oracle interface. Generated client name: `PriceOracleClient`.
#[contractclient(name = "PriceOracleClient")]
pub trait PriceOracle {
    fn lastprice(env: Env, asset: ReflectorAsset) -> Option<ReflectorPriceData>;
    fn decimals(env: Env) -> u32;
    fn last_timestamp(env: Env) -> u64;
    fn assets(env: Env) -> Vec<ReflectorAsset>;
}

/// Subscription-contract interface. Generated client name: `SubscriptionClient`.
#[contractclient(name = "SubscriptionClient")]
pub trait SubscriptionContractTrait {
    fn create_subscription(
        env: Env,
        new_subscription: SubscriptionInitParams,
        amount: u64,
    ) -> (u64, Subscription);
    fn deposit(env: Env, from: Address, subscription_id: u64, amount: u64);
    fn cancel(env: Env, subscription_id: u64);
    fn get_subscription(env: Env, subscription_id: u64) -> Subscription;
    fn get_retention_fee(env: Env, subscription_id: u64) -> u64;
    fn fee(env: Env) -> u64;
}

// ────────────────────────────────────────────────────────────────────────────
// Adapter abstraction (so contracts can swap in `mock::MockOracle` for tests)
// ────────────────────────────────────────────────────────────────────────────

/// Source of synchronous price reads. Real impl is [`ReflectorOracle`]; tests
/// use [`mock::MockOracle`].
pub trait OracleSource {
    /// Most recent price for `asset`, rescaled to `PRICE_SCALE`. Returns
    /// `None` if the oracle has no price for the asset.
    fn read_price(&self, env: &Env, asset: &ReflectorAsset) -> Option<PriceObservation>;
}

/// Source of subscription create/cancel ops. Real impl is [`ReflectorSubscription`];
/// tests use [`mock::MockSubscription`].
pub trait SubscriptionSource {
    fn create_subscription(
        &self,
        env: &Env,
        params: SubscriptionInitParams,
        amount: u64,
    ) -> (u64, Subscription);

    fn cancel(&self, env: &Env, subscription_id: u64);

    fn deposit(&self, env: &Env, from: &Address, subscription_id: u64, amount: u64);
}

/// Project-scale price observation. `price` is always at `PRICE_SCALE`.
#[contracttype]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct PriceObservation {
    /// Price at `PRICE_SCALE` (1e10).
    pub price: i128,
    /// Oracle's reported timestamp (seconds — the oracle stores ms internally
    /// but the contract surface returns the recorded `timestamp` field of
    /// `PriceData` unconverted; see Reflector source).
    pub timestamp: u64,
    /// Number of decimals reported by the oracle at the time of the read,
    /// captured for diagnostics. Not used to convert `price` again.
    pub oracle_decimals: u32,
}

/// Real Reflector price oracle bound to a deployed oracle contract address.
#[derive(Clone)]
pub struct ReflectorOracle {
    pub address: Address,
}

impl ReflectorOracle {
    pub fn new(address: Address) -> Self {
        Self { address }
    }
}

impl OracleSource for ReflectorOracle {
    fn read_price(&self, env: &Env, asset: &ReflectorAsset) -> Option<PriceObservation> {
        let client = PriceOracleClient::new(env, &self.address);
        let pd = client.lastprice(asset)?;
        let decimals = client.decimals();
        let scaled = rescale_to_price_scale(pd.price, decimals).ok()?;
        Some(PriceObservation {
            price: scaled,
            timestamp: pd.timestamp,
            oracle_decimals: decimals,
        })
    }
}

/// Real Reflector subscription contract bound to a deployed sub contract address.
#[derive(Clone)]
pub struct ReflectorSubscription {
    pub address: Address,
}

impl ReflectorSubscription {
    pub fn new(address: Address) -> Self {
        Self { address }
    }
}

impl SubscriptionSource for ReflectorSubscription {
    fn create_subscription(
        &self,
        env: &Env,
        params: SubscriptionInitParams,
        amount: u64,
    ) -> (u64, Subscription) {
        let client = SubscriptionClient::new(env, &self.address);
        client.create_subscription(&params, &amount)
    }

    fn cancel(&self, env: &Env, subscription_id: u64) {
        let client = SubscriptionClient::new(env, &self.address);
        client.cancel(&subscription_id);
    }

    fn deposit(&self, env: &Env, from: &Address, subscription_id: u64, amount: u64) {
        let client = SubscriptionClient::new(env, &self.address);
        client.deposit(from, &subscription_id, &amount);
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Scale helpers
// ────────────────────────────────────────────────────────────────────────────

/// Convert `oracle_price` (at `10.pow(decimals)`) to the project's `PRICE_SCALE`.
///
/// PRICE_SCALE is 1e10 (`PRECISION`). Reflector's pulse oracle reports prices
/// at `decimals = 14` so we generally divide by `10^4`. We handle the inverse
/// (oracle decimals < PRICE_SCALE exponent) too, by multiplying.
pub fn rescale_to_price_scale(oracle_price: i128, oracle_decimals: u32) -> Result<i128, MathError> {
    const PRICE_SCALE_EXP: u32 = 10; // 1e10
    if oracle_decimals == PRICE_SCALE_EXP {
        return Ok(oracle_price);
    }
    if oracle_decimals > PRICE_SCALE_EXP {
        let shift = oracle_decimals - PRICE_SCALE_EXP;
        let div = pow10_i128(shift)?;
        Ok(oracle_price / div)
    } else {
        let shift = PRICE_SCALE_EXP - oracle_decimals;
        let mul = pow10_i128(shift)?;
        oracle_price.checked_mul(mul).ok_or(MathError::Overflow)
    }
}

fn pow10_i128(exp: u32) -> Result<i128, MathError> {
    let mut acc: i128 = 1;
    for _ in 0..exp {
        acc = acc.checked_mul(10).ok_or(MathError::Overflow)?;
    }
    Ok(acc)
}

// Compile-time sanity: project price scale must be 1e10.
const _: () = assert!(PRICE_SCALE == 10_000_000_000);

#[cfg(test)]
mod scale_tests {
    use super::*;

    #[test]
    fn rescale_identity_at_10_decimals() {
        assert_eq!(rescale_to_price_scale(1_234_567_890_123, 10).unwrap(), 1_234_567_890_123);
    }

    #[test]
    fn rescale_down_from_14_decimals_pulse() {
        // Pulse oracle returns 14 decimals → divide by 10^4.
        let raw = 50_000_i128 * 100_000_000_000_000_i128; // BTC 50k at 1e14 = 5e18
        let scaled = rescale_to_price_scale(raw, 14).unwrap();
        assert_eq!(scaled, 50_000 * PRICE_SCALE);
    }

    #[test]
    fn rescale_up_from_7_decimals() {
        let raw = 12_345_678_i128; // 1.2345678 at 1e7
        let scaled = rescale_to_price_scale(raw, 7).unwrap();
        assert_eq!(scaled, 12_345_678_000_i128); // ×1e3 → 1e10
    }
}
